Develop
rusalforever/python-course-alphabet pull request #1
Opened 2019-04-19 10:16 UTC by rusalforever

2019-04-19 10:40 UTC, dvasilov commented on build_in_methods_iterators/homework.py
> +    minvalue = min(map(lambda x: x.get(key), data))
Ти можеш повернути одразу словник. Не потрібна ще одна ітерація по ньому

2019-04-19 10:40 UTC, dvasilov commented on build_in_methods_iterators/homework.py
> +    for data_dict in data:
В данній задачі можна використати dict comprehension. І розв'язок бути виглядати більш акуратно

2019-04-19 11:03 UTC, zulteg commented
Не могу почему то оставить коммент на строчке

`return random.sample(string.ascii_lowercase, 20)`
это решение интересное, но надо понимать, что он берет срез из перемешанного массива (т.е. там не будет повторяющихся элементов). и если бы было задание получить 40 элементов, то размера алфавита не хватило и выдало бы ошибку `ValueError`

2019-04-20 13:31 UTC, yuriimchg requested changes
загалом добре; основні зауваження залишив Денис

2019-04-20 13:31 UTC, yuriimchg commented on .gitignore
>  env
`No newline at end of the file`

2019-04-20 13:31 UTC, yuriimchg commented on build_in_methods_iterators/homework.py
> +    # if isinstance(key, str):
старайся прибирати закоментований код - якраз для того, щоб за потреби відкотитися до попередньої версії ми використовуємо Git

2019-04-21 10:41 UTC, yuriimchg approved these changes
:+1:

2019-04-21 16:32 UTC, merged

2019-04-22 21:10 UTC, nonstop132 commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW2_Python_functionality](https://trello.com/c/P0WZ1Xhh/46-hw2pythonfunctionality)

2019-04-24 12:32 UTC, nonstop132 commented
![](https://github.trello.services/images/mini-trello-icon.png) [HW2_Python_functionality](https://trello.com/c/P0WZ1Xhh/46-hw2pythonfunctionality)