Finished HW5
rusalforever/python-course-alphabet pull request #4
Opened 2019-05-13 17:22 UTC by rusalforever

2019-05-18 14:16 UTC, yuriimchg requested changes
привіт, я нарешті порев'ювив код, вибач за затримку.
Моє враження: виглядає дуже класно і професійно;
 сама ідея наслідувати класи від конвертерів виглядає дуже цікаво + це запобігає дублюванню коду. 
 є декілька нюансів, які мені не до кінця зрозумілі або які варто пофіксити - тому кидаю request changes

2019-05-18 14:16 UTC, yuriimchg commented on serialization/homework.py
> +from constants import TOWNS, CARS_TYPES, CARS_PRODUCER
https://www.python.org/dev/peps/pep-0008/#imports

Imports should be grouped in the following order:

Standard library imports.
Related third party imports.
Local application/library specific imports.
You should put a blank line between each group of imports.

2019-05-18 14:16 UTC, yuriimchg commented on serialization/homework.py
> +    @classmethod
тут і в наступних методах краще було би вказувати `GenericJSONDecoder` дефолтним значенням параметра `cls` основного методу, оскільки в такій реалізації дефолтний параметр не має ефекту ти матимеш те значення, яке передаєш

2019-05-18 14:16 UTC, yuriimchg commented on serialization/homework.py
> +    def decode(self, str):
`str` - зарезервоване ім'я для типу даних, тому краще використати якесь інше (можна `string`)

2019-05-18 14:16 UTC, yuriimchg commented on serialization/homework.py
> +            '__name__': cls.__name__,
```suggestion
            'name': cls.__name__,
```

2019-05-18 14:16 UTC, yuriimchg commented on serialization/homework.py
> +            return stream.getvalue()
у випадку `else`(коли `inefficient = False` варто передати повідомлення про помилку)

2019-05-18 14:16 UTC, yuriimchg commented on serialization/homework.py
> +                    v = list(v)
для чого тут конвертація значення до типу `list`, якщо воно вже й так його має?

2019-05-18 15:52 UTC, rusalforever commented on serialization/homework.py
> +    @classmethod
тут так і робиться

2019-05-18 15:56 UTC, rusalforever commented on serialization/homework.py
> +            '__name__': cls.__name__,
тут це для більшої наглядності в JSON предаставленні що це назва класу

2019-05-19 09:48 UTC, yuriimchg commented on serialization/homework.py
> +            '__name__': cls.__name__,
окей

2019-05-19 09:51 UTC, yuriimchg approved these changes
:+1:

2019-05-20 16:13 UTC, merged