Done HW6
rusalforever/python-course-alphabet pull request #5
Opened 2019-05-18 16:52 UTC by rusalforever

2019-05-18 20:36 UTC, yuriimchg requested changes
привіт, я переглянув твою роботу
все працює :+1: 

якщо маєш час / натхнення / бажання, можеш спробувати замінити `if / else` в кількох методах на якусь цікавішу і більш оптимальну реалізацію
+ покращити методи для зміни енергії в кота

також старайся уникати рядків, довших за 79 символів (pep-8), де це можливо
обов'язково треба пофіксити метод, який повертає кількість ролів шпалер - вона має бути цілою

решта - на твій розсуд

2019-05-18 20:36 UTC, yuriimchg commented on oop/homework.py
> +        return int(sum([wall.number_of_rolls_of_wallpaper(roll_width_m, roll_length_m) for wall in self.__walls]))
для чого тут ще конвертація в `int`?
хіба результат number_of_rolls_of_wallpaper не є цілим числом?

2019-05-18 20:36 UTC, yuriimchg commented on oop/homework.py
> +            raise ValueError("Sorry we don't have such material")
ексепшни не надто інформативні, оскільки не вказано, який матеріал може бути ок
це також стосується інших ексепшнів
і, скоріше за все, це інформація на майбутнє, оскільки в завданні про це нічого не казалося

2019-05-18 20:36 UTC, yuriimchg commented on oop/homework.py
> +        return self.wall_square() / (roll_width_m * roll_length_m)
тут виходить, що кількість ролів шпалер може бути нецілою, що впринципі не ок

2019-05-20 15:32 UTC, rusalforever commented on oop/homework.py
> +        return int(sum([wall.number_of_rolls_of_wallpaper(roll_width_m, roll_length_m) for wall in self.__walls]))
логічно має бути цілим але інакше тести не проходять (про це попереджалось на лекції)

2019-05-20 15:33 UTC, rusalforever commented on oop/homework.py
> +            raise ValueError("Sorry we don't have such material")
також виведено повідомлення яке вимагалось в завданні, кастомної логіки тут нема ніде

2019-05-20 16:05 UTC, rusalforever commented on oop/homework.py
> +        return self.wall_square() / (roll_width_m * roll_length_m)
так стояла задача інакше тести падають, сам я це розумію

2019-05-21 06:32 UTC, merged